
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    sort_pub_dependencies: false
    always_use_package_imports: true
    prefer_single_quotes: true
